import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AdPopupProvider } from "@/components/adsterra/AdPopupProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FF Emote Bot",
  description: "Generated by create next app",
  other: {
    "google-adsense-account": "ca-pub-3046143154826584",
    "monetag": "3d4f03180e51b4e6d712438addcde80d",
    "1a6900f5d82e5492a6fd434f5ec2b3930ff78ce4": "1a6900f5d82e5492a6fd434f5ec2b3930ff78ce4",
    "referrer": "no-referrer-when-downgrade"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
        <AdPopupProvider />
      </body>
    </html>
  );
}
